"""empty message

Revision ID: 320b7a437f2e
Revises: 9bd17e73ad17
Create Date: 2023-03-01 19:04:23.715816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320b7a437f2e'
down_revision = '9bd17e73ad17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
