"""empty message

Revision ID: 67880d0d7b73
Revises: bc0cea36117e
Create Date: 2023-02-08 19:54:45.476568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67880d0d7b73'
down_revision = 'bc0cea36117e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
