"""empty message

Revision ID: 6d0c1332c5fb
Revises: 67880d0d7b73
Create Date: 2023-02-08 20:36:40.492130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d0c1332c5fb'
down_revision = '67880d0d7b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('images',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.alter_column('images',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
