"""empty message

Revision ID: b15c1cbff789
Revises: d035347b79f7
Create Date: 2023-02-13 19:32:18.912087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b15c1cbff789'
down_revision = 'd035347b79f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cache', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cache', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=sa.String(length=255),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    # ### end Alembic commands ###
