"""empty message

Revision ID: db2e4d0485a9
Revises: 79a1a1f9338a
Create Date: 2023-02-03 19:02:08.398267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db2e4d0485a9'
down_revision = '79a1a1f9338a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'blog', ['id'])
    op.drop_column('favorite', 'id')
    op.alter_column('user', 'ig',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'fb',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'twitter',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'twitter',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'fb',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'ig',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('favorite', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'blog', type_='unique')
    # ### end Alembic commands ###
